export const MfeConfig = {
    "host":{
         "url":"http://localhost:8080/remoteEntry.js"
    },
    "dashboard":{
         "url":"Dashboard@http://localhost:8002/remoteEntry.js"
    },
    "rdsComponents":{
         "url":"http://localhost:8001/remoteEntry.js"
    },
    "maintainance":{
         "url":"http://localhost:8005/remoteEntry.js"
    },
    "forgotpassword":{
         "url":"ForgotPassword@http://localhost:8003/remoteEntry.js"
    },
    "login":{
         "url":"Login@http://localhost:8004/remoteEntry.js"
    }
}