export const MfeConfig = {
	"host":{
		 "url":"http://localhost:8080/remoteEntry.js"
	},
	"edition":{
		"url":"edition@http://localhost:8001/remoteEntry.js"
	},
	"dashboard":{
		 "url":"dashboard@http://localhost:8002/remoteEntry.js"
	},
	"forgotpassword":{
		 "url":"forgotpassword@http://localhost:8003/remoteEntry.js"
	},
	"login":{
		 "url":"login@http://localhost:8004/remoteEntry.js"
	},
	"maintainance":{
		"url":"maintainance@http://localhost:8005/remoteEntry.js"
	},
	"tenant":{
		"url":"tenant@http://localhost:8006/remoteEntry.js"
	},
	"visualSetting":{
		"url":"visualSetting@http://localhost:8007/remoteEntry.js"
	},
	"webhookSubscription":{
		"url":"webhookSubscription@http://localhost:8008/remoteEntry.js"
	},
	"auditLogs":{
		"url":"auditlogs@http://localhost:8009/remoteEntry.js" 
	},
	"settings":{
		"url":"settings@http://localhost:8010/remoteEntry.js"
	},
	"users":{
		"url":"users@http://localhost:8015/remoteEntry.js"
	},
	"roles":{
		"url":"roles@http://localhost:8012/remoteEntry.js"
	},
	"organizationUnits":{
		"url":"organizationUnits@http://localhost:8013/remoteEntry.js"
	},
	"language":{
		"url":"language@http://localhost:8014/remoteEntry.js"
	}
}