import React from "react";
import { ComponentStory, ComponentMeta } from "@storybook/react";
import RdsIcon from "./rds-icon";

export default {
  title: "Elements/Icon",
  component: RdsIcon,
  argTypes: {
    name: {
      options: [
        ,
        "action",
        "administration",
        "api_referances",
        "arrow_down",
        "arrow_left",
        "arrow_right",
        "arrow_up",
        "audit_logs",
        "award",
        "bag",
        "bar_chart",
        "basic_subscription",
        "blog",
        "book",
        "books",
        "brush",
        "calendar",
        "camera",
        "cancel",
        "card_data",
        "card_image",
        "careers",
        "cc",
        "check",
        "check_square",
        "chevron_down",
        "chevron_left",
        "chevron_right",
        "chevron_up",
        "circle",
        "circles",
        "clipboard",
        "clipboard_check",
        "clipboard_data",
        "clock",
        "close",
        "close_circle",
        "cloud_download",
        "cloud_upload",
        "code",
        "code_computer",
        "code_square",
        "computer",
        "cookies",
        "countries",
        "crop",
        "currency_dollar",
        "currency_dollar_circle",
        "customer",
        "daily_sales",
        "dashboard_settings",
        "daily_sales",
        "dashboard_settings",
        "date_picker",
        "delete",
        "delete_file",
        "demo_ui",
        "direction",
        "dislike",
        "dollar",
        "down",
        "down_arrow",
        "download",
        "download_data",
        "download_receipt",
        "dynamic_properties",
        "edit",
        "editions",
        "empty_states_add_section",
        "empty_states_add_nodes",
        "empty_states_add_card",
        "empty_states_add_records",
        "empty_states_add_screens",
        "envelope",
        "exchange",
        "exclamation_circle",
        "exclamation_diamond",
        "exclamation_triangle",
        "export",
        "export_data",
        "eye",
        "eye_slash",
        "featured",
        "features",
        "file",
        "file_data",
        "file_plus",
        "filter",
        "folder",
        "folder_search",
        "fullscreen",
        "fullscreen_square",
        "funnel",
        "gear",
        "users"
      ],
      control: {
        type: "select",
      },
    },
  },
} as ComponentMeta<typeof RdsIcon>;

const Template: ComponentStory<typeof RdsIcon> = (args) => (
  <RdsIcon {...args} />
);

export const Default = Template.bind({});
Default.args = {
  name: "book",
  width: '20px',
  height:"20px"
};
